version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-eventbridge-nyc-market"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fu356qim4goz"
s3_prefix = "sam-eventbridge-nyc-market"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "NYCMarketDestinationURL=\"https://webhook.site/e15edb58-7f6b-485d-ab56-c7e614c9c32c\""
image_repositories = []
