AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  OrderManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambda.handler
      PackageType: Zip
      Runtime: nodejs16.x
      MemorySize: 128
      Timeout: 500
      Events:
        AppEventAPI:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AppEventAPI:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  OrderManagerFunction:
    Description: "OrderManagerFunction ARN"
    Value: !GetAtt OrderManagerFunction.Arn
  OrderManagerFunctionIamRole:
    Description: "Implicit IAM Role created for OrderManagerFunction"
    Value: !GetAtt OrderManagerFunctionRole.Arn